import shutil
from pathlib import Path
from datetime import datetime
import logging
from log_manager import setup_logging # Import the setup_logging function

class VaultSkills:
    """Collection of skills for vault operations."""

    def __init__(self, vault_path: str = "AI_Employee_Vault"):
        self.vault_path = Path(vault_path)
        self.inbox = self.vault_path / "Inbox"
        self.needs_action = self.vault_path / "Needs_Action"
        self.done = self.vault_path / "Done"
        self.dashboard = self.vault_path / "Dashboard.md"
        # The Plan.md will be directly in Needs_Action as per requirements
        self.plans_dir = self.vault_path / "Needs_Action" # Plans will be written directly here

        # Setup logger for VaultSkills (Silver Tier log path)
        self.logger = setup_logging(log_file="logs/ai_employee.log", logger_name="vault_skills")
        self.logger.info("VaultSkills initialized and logging set up.")

        # Ensure folders exist
        self.inbox.mkdir(parents=True, exist_ok=True)
        self.needs_action.mkdir(parents=True, exist_ok=True)
        self.done.mkdir(parents=True, exist_ok=True)
        self.logger.debug(f"Ensured vault directories exist: {self.inbox}, {self.needs_action}, {self.done}")

    def read_task(self, file_name: str) -> dict:
        """
        Read a task file from Needs_Action folder.

        Args:
            file_name: Name of the file (e.g., 'task_001.md')

        Returns:
            Dictionary with task content and metadata
        """
        file_path = self.needs_action / file_name

        if not file_path.exists():
            self.logger.error(f"Task file not found: {file_name}")
            return {"error": f"Task file not found: {file_name}"}

        content = file_path.read_text()

        # Parse frontmatter (YAML between ---)
        metadata = {}
        body = content

        if content.startswith("---"):
            parts = content.split("---", 2)
            if len(parts) >= 3:
                frontmatter = parts[1].strip()
                body = parts[2].strip()

                for line in frontmatter.split("\n"):
                    if ":" in line:
                        key, value = line.split(":", 1)
                        metadata[key.strip()] = value.strip()

        self.logger.info(f"Read task file: {file_name}")
        return {
            "file_name": file_name,
            "metadata": metadata,
            "body": body,
            "full_content": content
        }

    def write_response(self, file_name: str, response: str, action_items: list = None) -> str:
        """
        Write a response to a task file.

        Args:
            file_name: Name of the task file
            response: The AI's response/content
            action_items: List of action items (checkboxes)

        Returns:
            Status message
        """
        file_path = self.needs_action / file_name

        if not file_path.exists():
            self.logger.error(f"Error: Task file not found: {file_name}")
            return f"Error: Task file not found: {file_name}"

        # Read original content
        original = file_path.read_text()

        # Append response
        response_section = f"""

---
## AI Response
**Generated:** {datetime.now().isoformat()}

{response}

"""

        if action_items:
            response_section += "### Action Items\n"
            for item in action_items:
                response_section += f"- [ ] {item}\n"

        try:
            file_path.write_text(original + response_section)
            self.logger.info(f"Response written to {file_name}")
            return f"Response written to {file_name}"
        except Exception as e:
            self.logger.error(f"Error writing response to {file_name}: {e}")
            return f"Error writing response: {e}"

    def write_plan(self, original_task_file_name: str, plan_content: str) -> str:
        """
        Write a plan file (Plan.md) to the Needs_Action folder.
        The Plan.md should be associated with the original task.

        Args:
            original_task_file_name: The name of the original task file (e.g., 'EMAIL_client_request.md').
            plan_content: The step-by-step plan generated by the AI.

        Returns:
            Path to the plan file or an error message.
        """
        # Create Plan.md in Needs_Action, potentially with a reference to the original task
        plan_file_name = f"Plan_{Path(original_task_file_name).stem}.md"
        plan_file_path = self.needs_action / plan_file_name

        try:
            plan_file_path.write_text(plan_content)
            self.logger.info(f"Plan generated and written to {plan_file_path.name} in Needs_Action.")
            return str(plan_file_path)
        except Exception as e:
            self.logger.error(f"Error writing plan to {plan_file_path.name}: {e}")
            return f"Error writing plan: {e}"

    def move_to_done(self, file_name: str, summary: str = None) -> str:
        """
        Move a completed task to the Done folder.

        Args:
            file_name: Name of the file to move
            summary: Optional completion summary

        Returns:
            Status message
        """
        source = self.needs_action / file_name
        dest = self.done / file_name

        if not source.exists():
            self.logger.error(f"Error: File not found in Needs_Action: {file_name}")
            return f"Error: File not found in Needs_Action: {file_name}"

        # Add completion metadata if summary provided
        if summary:
            content = source.read_text()
            content += f"""

---
## Completed
**Completed:** {datetime.now().isoformat()}
**Summary:** {summary}
"""
            try:
                source.write_text(content)
                self.logger.debug(f"Added completion summary to {file_name}")
            except Exception as e:
                self.logger.error(f"Error writing summary to {file_name}: {e}")
                return f"Error adding summary: {e}"

        # Move file
        try:
            shutil.move(str(source), str(dest))
            self.logger.info(f"Moved {file_name} from Needs_Action to Done folder.")
            return f"Moved {file_name} to Done folder"
        except Exception as e:
            self.logger.error(f"Error moving {file_name} to Done: {e}")
            return f"Error moving file: {e}"

    def move_to_needs_action(self, file_name: str) -> str:
        """
        Move a file from Inbox to Needs_Action.

        Args:
            file_name: Name of the file to move

        Returns:
            Status message
        """
        source = self.inbox / file_name
        dest = self.needs_action / file_name

        if not source.exists():
            self.logger.error(f"Error: File not found in Inbox: {file_name}")
            return f"Error: File not found in Inbox: {file_name}"

        try:
            shutil.move(str(source), str(dest))
            self.logger.info(f"Moved {file_name} from Inbox to Needs_Action folder.")
            return f"Moved {file_name} to Needs_Action folder"
        except Exception as e:
            self.logger.error(f"Error moving {file_name} to Needs_Action: {e}")
            return f"Error moving file: {e}"

    def update_dashboard(self, section: str, content: str) -> str:
        """
        Update a section of the Dashboard.md file.

        Args:
            section: Section name to update
            content: New content for the section

        Returns:
            Status message
        """
        if not self.dashboard.exists():
            try:
                self.dashboard.write_text("# Dashboard\n\n")
                self.logger.info(f"Created new Dashboard.md.")
            except Exception as e:
                self.logger.error(f"Error creating Dashboard.md: {e}")
                return f"Error updating dashboard: {e}"

        current = self.dashboard.read_text()

        # Check if section exists
        section_header = f"## {section}"

        if section_header in current:
            lines = current.split("\n")
            new_lines = []
            in_section = False

            for line in lines:
                if line.startswith("## ") and section in line:
                    in_section = True
                    new_lines.append(section_header)
                    new_lines.append(content)
                elif in_section and line.startswith("## "):
                    in_section = False
                    new_lines.append(line)
                elif not in_section:
                    new_lines.append(line)

            try:
                self.dashboard.write_text("\n".join(new_lines))
                self.logger.info(f"Dashboard updated: {section} (existing section replaced).")
            except Exception as e:
                self.logger.error(f"Error updating existing dashboard section {section}: {e}")
                return f"Error updating dashboard: {e}"
        else:
            try:
                self.dashboard.write_text(current + f"\n{section_header}\n\n{content}\n")
                self.logger.info(f"Dashboard updated: {section} (new section added).")
            except Exception as e:
                self.logger.error(f"Error adding new dashboard section {section}: {e}")
                return f"Error updating dashboard: {e}"

        return f"Dashboard updated: {section}"

    def list_pending_tasks(self) -> list:
        """
        List all pending tasks in Needs_Action folder.

        Returns:
            List of task file names
        """
        if not self.needs_action.exists():
            self.logger.warning(f"Needs_Action directory does not exist: {self.needs_action}")
            return []

        tasks = [f.name for f in self.needs_action.iterdir() if f.suffix == ".md"]
        self.logger.info(f"Listed {len(tasks)} pending tasks in Needs_Action.")
        return tasks

    def get_task_summary(self) -> str:
        """
        Get a summary of all pending tasks.

        Returns:
            Formatted summary string
        """
        tasks = self.list_pending_tasks()

        if not tasks:
            return "No pending tasks."

        summary = f"**Pending Tasks:** {len(tasks)}\n\n"
        for task in tasks:
            task_data = self.read_task(task)
            task_type = task_data["metadata"].get("type", "unknown")
            priority = task_data["metadata"].get("priority", "normal")
            summary += f"- **{task}** (Type: {task_type}, Priority: {priority})\n"

        self.logger.info("Generated summary of pending tasks.")
        return summary


def read_file(file_path: Path) -> str:
    """Reads content of a given file path."""
    return file_path.read_text()

def move_file(source_path: Path, destination_path: Path):
    """Moves a file from source to destination."""
    shutil.move(str(source_path), str(destination_path))

# Convenience functions for direct import
_vault = None

def get_vault():
    """Get singleton vault instance."""
    global _vault
    if _vault is None:
        _vault = VaultSkills()
    return _vault

def read_task(file_name: str) -> dict:
    """Read a task from Needs_Action."""
    return get_vault().read_task(file_name)

def write_response(file_name: str, response: str, action_items: list = None) -> str:
    """Write a response to a task."""
    return get_vault().write_response(file_name, response, action_items)

def write_plan(original_task_file_name: str, plan_content: str) -> str:
    """Write a plan file (Plan.md) to the Needs_Action folder."""
    return get_vault().write_plan(original_task_file_name, plan_content)

def move_to_done(file_name: str, summary: str = None) -> str:
    """Move a task to Done folder."""
    return get_vault().move_to_done(file_name, summary)

def move_to_needs_action(file_name: str) -> str:
    """Move a file from Inbox to Needs_Action."""
    return get_vault().move_to_needs_action(file_name)

def update_dashboard(section: str, content: str) -> str:
    """Update dashboard section."""
    return get_vault().update_dashboard(section, content)

def list_pending_tasks() -> list:
    """List all pending tasks."""
    return get_vault().list_pending_tasks()

def get_task_summary() -> str:
    """Get summary of pending tasks."""
    return get_vault().get_task_summary()
